version: '1'

services:
  nestjs-app:
    build:
      context: student-record-backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres-db
    environment:
      DATABASE_HOST: postgres-db

  postgres-db:
    image: postgres:14-alpine
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: muaz
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: student_record_dev

  react-app:
    build:
      context: student-record-frontend
    ports:
      - '5173:5173'
    depends_on:
      - nestjs-app
    environment:
      - VITE_API_URL=http://localhost:3000
